### ISSUE TITLE
about the pre-trained weights

### ISSUE THREAD

**Issue by YukiFan** [pearl-robot-lab/neugraspnet#2]
When will the pre-trained network parameters be released? 
For example, the model file located at --model ./data/networks/neugraspnet_pile_efficient.pt.
Thanks~

**Comment by sjauhri** [comment]
Hi @YukiFan ,

The efficient network parameters you pointed out have already been released. They are the current best parameters to use. Other pre-trained networks provide almost the same performance but are not as fast.

**Comment by YukiFan** [comment]
Thank you for your reply. I found the pre-trained network weights.
